### ISSUE TITLE
Please Make it available for Flutter 3.22.2

### ISSUE THREAD

**Issue by muthukrishnanOCS** [mirzamahmud/qr_scanner_with_effect#2]
The library is good but its not available for flutter 3.22.2 and dart Dart 3.4.1

**Comment by mirzamahmud** [comment]
@muthukrishnanOCS Unfortunately, I forgot to maintain the repo. Thank you for your response, I will do it ASAP

**Comment by mirzamahmud** [comment]
@muthukrishnanOCS you can check now
